import "./globals.css";
import "/src/styles/sidebar.css";
import "/src/styles/header.css";
import "/src/styles/common-elements.css";
import "/src/styles/buttons.css";
import "/src/styles/forms.css";
import type { Metadata } from "next";
import Sidebar from "@/core/main/components/Sidebar";
import Header from "@/core/main/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div>
                    <Header />
                    
                    <div className="flex flex-row w-full h-full bg-white">
                        <Sidebar />

                        <div className="flex-1 w-full h-full">
                            <main>
                                {children}
                            </main>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
