import "./globals.css";
import "/src/styles/sidebar.css";
import "/src/styles/header.css";
import "/src/styles/common-elements.css";
import "/src/styles/buttons.css";
import "/src/styles/forms.css";
import "/src/styles/layout.css";
import type { Metadata } from "next";
import Sidebar from "@/core/main/components/sidebar/Sidebar";
import Header from "@/core/main/components/Header";
import Providers from "@/core/main/providers/Providers";
import UserbarWrapper from "@/core/user/components/UserbarWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <div>
                        <Header />
                        <UserbarWrapper />
                        
                        <div className="flex flex-row flex-grow overflow-hidden bg-white">
                            <div
                                className="fixed inset-y-0 left-0 z-40 md:static md:flex-none rounded-r-md"
                                style={{
                                    height: "calc(100vh - 4rem)",
                                    top: "4rem",
                                    backgroundColor: "var(--sidebar-bg-color)",
                                }}
                            >
                                <Sidebar />
                            </div>


                            <div
                                className="flex-grow overflow-y-auto overflow-x-none ml-12 md:ml-0 relative"
                                style={{ height: "calc(100vh - 4rem)" }}
                            >
                                {children}
                            </div>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
